services:
  db:
    image: postgres:16-alpine
    container_name: mintada-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mintada
      - POSTGRES_DB=mintada_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mintada-network

  api:
    build:
      context: .
      dockerfile: Presentation/Mintada.Api/Dockerfile
    container_name: mintada-api
    volumes:
      - ../images:/app/wwwroot/images
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mintada_db;Username=admin;Password=mintada
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - mintada-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: mintada-db-ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mintada.com
      - PGADMIN_DEFAULT_PASSWORD=mintada
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - mintada-network

  web:
    image: node:20-alpine
    container_name: mintada-web
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./Presentation/Mintada.Web:/app
      - /app/node_modules
    networks:
      - mintada-network

volumes:
  postgres_data:


networks:
  mintada-network:
    driver: bridge
